### PR TITLE
Added link to bootstrap js plugins. Beautified .html for easier reading

### PR DESCRIPTION
**Pull request by bniedermeyer**
According to Bootstraps documentation to have a the collapsed navbar expandable you need to include the Bootstrap javascript plugins in your page (see [Bootstrap's documentation here](https://getbootstrap.com/components/#navbar-default)). CodePen I believe sets these up by default and for some reason the link wasn't included the html you downloaded from the site. I've added it so the plugins load with the page and the navbar behaves as expected. 

I also ran the HTML through  the Atom Beautify tool so it will be easier for you to read as you make changes. The majority of the changes you see below are the alignment changes with the tags. The only actual text that has been changed is the addition of the link to the bootstrap file at the botom. 

If you'd rather I didn't let me know and I'll amend my request. Let me know if you have any questions!

### CODE REVIEW

**Comment by LupDre** [comment]
This looks great! Thank you very much!

I'm testing the modified code in Cloud9, since I'm at work right now, and the collapsed navbar button still isn't working. I think there's still an issue with my JavaScript code so that can be addressed in another commit.

Merging PR. Thanks so much, @bniedermeyer

**Comment by bniedermeyer** [comment]
@LupDre Double check the version of index.html you have on your c9 box and loaded on your site's server. I just did a quick compare of what's in your repo vs whats actually on http://luperdev.com/ and it looks like you are still missing the `<script>` tag I added that points to the bootstrap source. 

image

**Comment by LupDre** [comment]
Yeah I haven't had the chance to upload it to the server yet. Will do it soon.

**Comment by bniedermeyer** [comment]
If you're not doing anything super crazy with your portfolio you might want to consider looking into using [Github Pages](https://pages.github.com/) to host it. That way when you push to here it automatically builds it for you. I might be giving a talk about how to use it at a meetup next week. If you're interested let me know and as soon as I get confirmation for it I'll send you the details.

**Comment by LupDre** [comment]
I thought about that but I already have another project up on Github Pages, see LupDre.github.io in my projects. If I can host multiple sites on Github Pages that would be awesome but haven't figured out if I'm able to do that.

**Comment by LupDre** [comment]
w00t! That worked! Thanks for all your help @bniedermeyer

**Comment by bniedermeyer** [comment]
No problem!

**Pull request merged**
